"""create suppression_rules

Revision ID: 3c887ef15ca6
Revises: aff6521f9f1f
Create Date: 2026-09-26 20:51:28.227788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c887ef15ca6'
down_revision: Union[str, Sequence[str], None] = 'aff6521f9f1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppression_rules',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('src_ip', sa.String(length=45), nullable=True),
    sa.Column('signature_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_suppression_enabled_expires', 'suppression_rules', ['enabled', 'expires_at'], unique=False)
    op.create_index(op.f('ix_suppression_rules_signature_id'), 'suppression_rules', ['signature_id'], unique=False)
    op.create_index(op.f('ix_suppression_rules_src_ip'), 'suppression_rules', ['src_ip'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suppression_rules_src_ip'), table_name='suppression_rules')
    op.drop_index(op.f('ix_suppression_rules_signature_id'), table_name='suppression_rules')
    op.drop_index('idx_suppression_enabled_expires', table_name='suppression_rules')
    op.drop_table('suppression_rules')
    # ### end Alembic commands ###
