"""create alerts table

Revision ID: b85203759c0f
Revises:
Create Date: 2026-09-25 16:38:44.412811

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b85203759c0f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("source_engine", sa.String(length=16), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("src_ip", sa.String(length=45), nullable=False),
        sa.Column("src_port", sa.Integer(), nullable=True),
        sa.Column("dst_ip", sa.String(length=45), nullable=False),
        sa.Column("dst_port", sa.Integer(), nullable=True),
        sa.Column("protocol", sa.String(length=10), nullable=True),
        sa.Column("signature", sa.String(length=512), nullable=False),
        sa.Column("attack_type", sa.String(length=64), nullable=True),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("dedup_key", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_alerts_detected_severity", "alerts", ["detected_at", "severity"], unique=False
    )
    op.create_index(op.f("ix_alerts_attack_type"), "alerts", ["attack_type"], unique=False)
    op.create_index(op.f("ix_alerts_dedup_key"), "alerts", ["dedup_key"], unique=False)
    op.create_index(op.f("ix_alerts_detected_at"), "alerts", ["detected_at"], unique=False)
    op.create_index(op.f("ix_alerts_dst_port"), "alerts", ["dst_port"], unique=False)
    op.create_index(op.f("ix_alerts_severity"), "alerts", ["severity"], unique=False)
    op.create_index(op.f("ix_alerts_source_engine"), "alerts", ["source_engine"], unique=False)
    op.create_index(op.f("ix_alerts_src_ip"), "alerts", ["src_ip"], unique=False)
    op.create_index(op.f("ix_alerts_status"), "alerts", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alerts_status"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_src_ip"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_source_engine"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_severity"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_dst_port"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_detected_at"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_dedup_key"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_attack_type"), table_name="alerts")
    op.drop_index("idx_alerts_detected_severity", table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
